# About this notebook 

#### Feature: Description

This notebook employs tfidf vectorizer natural language processing (NLP) with a Naive-Bayes algorithm to predict adoption rate using the pet's description field.

<div class="span5 alert alert-success">
<p> <I> Feature Description: </I> The "Description" data is a profile write-up for each pet.
     <br>
    <I> Source: </I> https://www.kaggle.com/c/petfinder-adoption-prediction/data  </p>
</div>

<div class="span5 alert alert-success">
<p> <I> Predictor (Adoption Speed) Description: </I> 

Contestants are required to predict this value. The value is determined by how quickly, if at all, a pet is adopted.   
<br> 
The values are determined in the following way:   
0 - Pet was adopted on the same day as it was listed.    
1 - Pet was adopted between 1 and 7 days (1st week) after being listed.    
2 - Pet was adopted between 8 and 30 days (1st month) after being listed.    
3 - Pet was adopted between 31 and 90 days (2nd & 3rd month) after being listed.    
4 - No adoption after 100 days of being listed.    

</p>
</div>

In [1]:
import warnings
warnings.filterwarnings('ignore')

%cd C:\Users\Ken\Documents\KenP\Applications-DataScience\SpringboardCourseWork\CapstoneProject2Repository\09 PetfindersData\TrainingData

C:\Users\Ken\Documents\KenP\Applications-DataScience\SpringboardCourseWork\CapstoneProject2Repository\09 PetfindersData\TrainingData


<div class="span5 alert alert-info">
<p> <B>  Imports and Data Loading: </B>  </p>
</div>

In [2]:
#Imports
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB
import nltk

In [3]:
#Import the csv file

dfi = pd.read_csv('nlpinput.csv')

#remove the rows with no description 
dfi = dfi[pd.notnull(dfi.description)] 

dfi.head(1)

Unnamed: 0                                        description  \
0           0  Milo went missing after a week with her new ad...   

   adoptionspeed                                     tokenized_desc  
0              3  milo', 'went', 'missing', 'after', 'a', 'week'...

In [4]:
#Create dataframe of pet description feature
dfd = dfi[['description','adoptionspeed','tokenized_desc']]

dfd.head(1)

description  adoptionspeed  \
0  Milo went missing after a week with her new ad...              3   

                                      tokenized_desc  
0  milo', 'went', 'missing', 'after', 'a', 'week'...

In [5]:
#Create y
y = dfd.adoptionspeed

In [18]:
# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(dfd['description'], y, test_size = 0.33, random_state = 53)


In [19]:
# Initialize a CountVectorizer object
count_vectorizer = CountVectorizer(stop_words='english')

In [20]:
# Transform the training data using only the 'text' column values to create a bag of words vectors
count_train = count_vectorizer.fit_transform(X_train.values)

In [21]:
# Transform the test data using only the 'text' column values to create a bag of words vectors
count_test = count_vectorizer.transform(X_test.values)


In [22]:
# Instantiate a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()

In [23]:
# Fit the classifier to the training data
nb_classifier.fit(count_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [24]:
# Create the predicted tags
pred = nb_classifier.predict(count_test)

In [25]:
# Calculate the accuracy score
score = metrics.accuracy_score(y_test,pred)
print(score)

0.35962783171521034


In [26]:
# Calculate the confusion matrix: cm
cm = metrics.confusion_matrix(y_test,pred,labels=[0,1,2,3,4])
print(cm)

[[  5  33  33  19  41]
 [  4 257 348 129 280]
 [  2 220 516 260 392]
 [  0 126 321 301 292]
 [  3 177 301 185 699]]
